#!/usr/bin/env python3
# ============================================================================
#  bmp2array.py — BMP 文件 → C 数组头文件 (供 03_photo 的 photo_data.h 使用)
#
#  用法:  python tools/bmp2array.py <input.bmp> <output.h>
#  示例:  python tools/bmp2array.py photo.bmp arm-dev/03_photo/photo_data.h
#
#  输出格式与 photo_data.h 一致: PHOTO_BMP_SIZE 宏 + photo_bmp[] 数组
# ============================================================================
import sys


def main():
    if len(sys.argv) != 3:
        print("usage: bmp2array.py <input.bmp> <output.h>")
        sys.exit(1)
    src, out = sys.argv[1], sys.argv[2]

    with open(src, "rb") as f:
        data = f.read()

    lines = ["// Auto-generated by tools/bmp2array.py — do not edit"]
    lines.append("#define PHOTO_BMP_SIZE %d" % len(data))
    lines.append("static const uint8_t photo_bmp[] = {")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ",".join("0x%02X" % b for b in chunk) + ",")
    lines.append("};")

    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")

    print("%s (%d bytes) -> %s" % (src, len(data), out))


if __name__ == "__main__":
    main()
